module.exports = {
  NOTIFICATION_TYPES: {
    MISCELLANEOUS: 'MISCELLANEOUS',
    SMS: 'SMS',
    EMAIL: 'EMAIL',
    SLACK: 'SLACK',
    WHATSAPP: 'WHATSAPP',
  },
  NOTIFICATION_SOURCE: {
    CRON_JON: 'CRON_JOB',
    ADMIN_API: 'ADMIN_API',
  },
  NOTIFICATION_STATUS: {
    WAITING_FOR_DELIVERY: 'WAITING_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    FAILED: 'FAILED',
    NOT_SUBSCRIBED: 'NOT_SUBSCRIBED',
  },
};
